# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 616335aae8ec4ceec88306ed314a13fc5d6d15e2677d3744d3a6457a5868fddcfe15254b370751c3bd8d1cbe4529e155d9add8e56702d5dbcabf3ca55c4b1c4f

test:
  secret_key_base: dea955691757d8455d53ec2a53a03f289d9c700fe0ef7d77154c14f65b12f0f718cb7281746fc10f61a282456780c502f7f33be840e0db6e66f14db266ca1491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
